### ISSUE TITLE
how to access reversals

### ISSUE THREAD

**Issue by dokato** [hadrienj/StaircaseJS#2]
Hi @hadrienj thanks for a great piece of code.

I want to utilize it for my task, but couldn't figure out from your documentation how to access the stopping criterion in the loop to interrupt the procedure after say 10 reversals.

Have a look at simple example with RDK task:

```js
var stairs = new Staircase({
    coh: {
    firstVal: 0.5,
    stepSizeDown: 0.025,
    limits: [0, 1],
    stepSizeUp: 0.05,
    reversalLimit: 10
  }
});

stairs.init();

var block = {
    type: "RDK",
    choices: ['z', 'm'],
    correct_choice: "m",
    coherence: function(){
        return stairs.getLast('coh');
    },
    aperture_type: 4,
    border: true,
    coherent_direction: 0,
    trial_duration: -1,
};

var loop_node = {
    timeline: [block],
    loop_function: function(data){
        var answer = data.values()[0].correct;
        stairs.next(answer);
        console.log(stairs.getActive().reversals);
        //if (stairs.reversalLimitReached(stair)) return false;
        return true;
    }
}
```

Here, whenever choice sequence I do, I always get `stairs.getActive().reversals` = 0.

I also don't understand what parameter `reversalLimitReached` expects? Why it can't just check if reversal what reached based on data stored in `this.stair`. I'd appreciate your answer :)

**Comment by hadrienj** [comment]
Hi @dokato, thanks for using the library. The method `reversalLimitReached()` expects the staircase as a parameter. In your case, it is `"coh"` (the key in the dictionary when you instantiated the staircase). So you can use like this:

```
stairs.reversalLimitReached("coh")
```

To get the number of reversals, I think you could use `stairs.getReversals("coh")`.

The method `getActive()` is used in the case where you have multiple interleaved staircases.

**Comment by dokato** [comment]
Great, that's exactly what I missed, thank you :)

**Comment by hadrienj** [comment]
Great! I'm happy if it solved your problem!
