### ISSUE TITLE
randInt in changeActive

### ISSUE THREAD

**Issue by dokato** [hadrienj/StaircaseJS#3]
Hi @hadrienj , it's me again. I noticed that in changeActive there is a little error. This:

https://github.com/hadrienj/StaircaseJS/blob/master/Staircase.js#L265

should be:

```js
  var rand = randInt(0, possibleStairs.length-1);
```

instead.

**Comment by hadrienj** [comment]
Thanks! I just fixed this! Tell me if you encounter any other issues!
